# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sathyadev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: declare-results
# "service" is the name of this project. This will also be added to your AWS resource names.
service: declare-results

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: !Ref declare-results
          topicName: mydeclare-results
