org: sathyadev
app: declare-results
service: declare-results

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: !Ref DeclareResultsSNSTopic
          topicName: mydeclare-results

resources:
  Resources:
    DeclareResultsSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: mydeclare-results
